const LANGUAGES = {
    "pl-PL": {
        "nickname": "Twój nick:",
        "ready?": "Gotowy?:",
        "ready": "gotowy",
        "not-ready": "nie gotowy",
        "players": "Gracze:",
        "you": "Ty",
        "roll": "RZUT KOSTKĄ",
        '1': 'jeden',
        '2': 'dwa',
        '3': 'trzy',
        '4': 'cztery',
        '5': 'pięć',
        '6': 'sześć',
        'winner': 'Zwycięzca: ',
        'red': 'czerwony',
        'blue': 'niebieski',
        'green': 'zielony',
        'yellow': 'żółty',
    },
    "en-US": {
        "nickname": "Your name:",
        "ready?": "Ready?:",
        "ready": "ready",
        "not-ready": "not ready",
        "players": "Players:",
        "you": "You",
        "roll": "ROLL DICE",
        '1': 'one',
        '2': 'two',
        '3': 'three',
        '4': 'four',
        '5': 'five',
        '6': 'six',
        'winner': 'Winner: ',
        'red': 'red',
        'blue': 'blue',
        'green': 'green',
        'yellow': 'yellow',
    }
}

export default LANGUAGES;
